### ISSUE TITLE
Using drawable resource is not supported 

### ISSUE THREAD

**Issue by Vad1mo** [jasonpolites/gesture-imageview#18]
Hello Jason,

I changed from a simple drawable to a [drawable resource](http://developer.android.com/guide/topics/resources/drawable-resource.html)

the result was that nothing was drawn but also there weren't any errors. 

This is the setup:
main.xml

``` XML
    <com.polites.android.GestureImageView
        android:id="@+id/my_id"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:layout_weight="0.9"
        android:adjustViewBounds="true"
        android:src="@drawable/simple_layer" />
```

drawable/simple_layer.xml

``` XML
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android" >
    <!-- <item -->
    <!-- android:id="@[+][package:]id/resource_name" -->
    <!-- android:bottom="dimension" -->
    <!-- android:drawable="@[package:]drawable/drawable_resource" -->
    <!-- android:left="dimension" -->
    <!-- android:right="dimension" -->
    <!-- android:top="dimension"/> -->

    <item android:src="@drawable/img1"/>
    <item android:src="@drawable/img2"/>
</layer-list>
```

I checked  onDraw, onLayout and on onMessuere by directing directly to the parent imageview but in all cases id didn't change the result. 

Do you have any ideas what it might be that caused not to display the drawables?

**Comment by jasonpolites** [comment]
Yeah.. that's a limitation as listed in the README but it really should work.  I think this limitation was there in an older version that was using a Bitmap rather than a Drawable but it's since been changed to just use a Drawable so there should not really be a reason it doesn't work.

I'll have to do some tests locally to see what's up.

**Comment by jasonpolites** [comment]
Oops.. just found the reason:

https://github.com/jasonpolites/gesture-imageview/blob/master/main/src/com/polites/android/GestureImageView.java#L365

This is left over code.  It should be:

``` java
setImageDrawable(getContext().getResources().getDrawable(id));
```

I will make these changes and create a test case in the sample app for a layer drawable.  You should be able to make these changes yourself and just merge later once I am ready to release

**Comment by jasonpolites** [comment]
Note:

There are a few other wacky things going on that I've just found.  I'll try to ship an update tonight with some fixes.

**Comment by Vad1mo** [comment]
Now I see something. 

One issue you might already noticed is that smaller drawables on a big drawable are stretched to full width and height.

until you provide parameters and gravity.

``` xml
    <item android:left="29px" android:top="199px" >
        <bitmap 
            android:gravity="left"
            android:src="@drawable/icon" />
    </item>
```

this is a workaround :)
