### ISSUE TITLE
Need help setting scale programmatically

### ISSUE THREAD

**Issue by winryan** [jasonpolites/gesture-imageview#19]
Hi there and thanks so much for taking your time to help others and sharing your hard work.  I am still quite new to android programming and I know this is probably silly and obvious, but how do I set the images zoom level on the first load if I wanted it to be zoomed to a certain location in the image at a particular scale?  I've tried setscale(XXX) with different values for XXX and have tried to use the redraw() method (along with any others I thought might do it) but I can't figure it out.  I know you're working to update the project tonight and I don't want to slow you down, but I'd appreciate it if you could help me out with this simple task (*doh) when you have a second.  Thank you!

**Comment by jasonpolites** [comment]
Hmm.. setScale along with setPosition should work.

Can you post the code you are using?

**Comment by winryan** [comment]
Sure,

I have the GestureImageView created in the layout although I set the source in the activity code.  I was setting the source image from the xml layout before but I'm trying everything I can think of haha.  Here is the current activity code, but when I run it, it always starts the image to fit the screen, no matter what I change, it seems.  I haven't tried to mess with the position yet, just the zoom (scale).

```
    setContentView(R.layout.map);
    GestureImageView GIV = (GestureImageView) findViewById(R.id.GIV1);
    GIV.setImageDrawable(getResources().getDrawable(R.drawable.greatmap));
    // GIV.setMinScale(1f);
    // GIV.setMaxScale(10f);
    GIV.setScale(20f);
    GIV.redraw();
    // GIV.setStrict(false);
    // GIV.setRecycle(true);
    // GIV.setAdjustViewBounds(true);
```

**Comment by jasonpolites** [comment]
mm.. probably due to the default ScaleType.  Try this:

``` java
GIV.setScaleType(ScaleType.CENTER);
```

**Comment by winryan** [comment]
That did work. I'll just use that as a refresh after setting the scale value.  Do you think there is another super.XXX (within a method like update scale or something) that could be added to be called from within GestureImageView that wouldn't feel as dirty?  :)  It's not a big deal honestly, the scaletype did the trick...

**Comment by winryan** [comment]
Actually I take it back...that unfortunately did not cause it to scale.  If I remove the scale statement and only use the getScaleType method, it does start the image a bit zoomed so I mistook that for it zooming from the scale command...so still stuck.  I'll keep experimenting and let you know if I find something that will update the scale factor programmatically.  Thanks again...

**Comment by winryan** [comment]
What I did to accomplish this (which is messy but works for now, is to add a method to the GestureImageView called setStartingScale(float startScale) that just changes the global startingScale value.  Each of the 3 ScaleTypes will always overwrite the startingScale value when the GestureImageView is initially laid out, so I commented out the line that would overwrite the startingScale value within the case for CENTER.  Now I just make sure to initially use my setStartingScale to the value I desire and setScale to CENTER and it will initially be zoomed to my desired result.  I hope that made sense...I haven't deciphered your code completely, or else I could do this more cleanly by redrawing etc (which I believe requires a message Handler instead of communicating directly with the GestureImageView from the activity) and also a perfect understanding of all your code and I'm not there yet...Once I do this right, I'll let you know, although not sure if you'd want to add the functionality of manipulating the GestureImageView programmatically to this project as that might be out of the scope of your aim here.)  

Ryan

**Comment by jasonpolites** [comment]
Hi Ryan,

I'll see if I can implement a way for this to work.  Ideally you should be able to just set the scale (at any time) and have it work as you expect.

For reference, the "redraw()" method on the GestureImageView does post a message asynchronously so you should be able to call that at any time with confidence (and from any thread)
