### ISSUE TITLE
zoom control buttons

### ISSUE THREAD

**Issue by tuffyg** [jasonpolites/gesture-imageview#2]
please could you add zoom control buttons for devices that do not support multi touch (there are a few running android 2.2)
they can be either the zoom controls provided within android or custom zoom in and out buttons.

any help asap would be appreciated
thanks

**Comment by jasonpolites** [comment]
I'll look at adding this for the next update.  Just added fling gesture for panning btw :)

**Comment by tuffyg** [comment]
nice.
thanks for the update. do you know how long it will take? also could you let me know when it is done please.
thank you

**Comment by jasonpolites** [comment]
Not sure when this will be done.  In the interim you can just add the default Android ZoomControls to the view in which you are rendering the image.  Simply call setScale() on the GestureImageView instance in the ZoomControls listener.

**Comment by jasonpolites** [comment]
Out of scope for GestureImageView.  Zoom controls can be added by the developer as standard UI controls and just call methods on the image view to control zoom.
