### ISSUE TITLE
Zoom to a certain point with zoom animation

### ISSUE THREAD

**Issue by Vad1mo** [jasonpolites/gesture-imageview#20]
Hello Jason.
I tried out your yesterdays commit. And i have question about the image view position change during animation.

What I want  to achieve is to zoom in to a certain position so that my newX and newY are on displays top left corner.

this is what I was using in the doubletaplistener

``` java
float scale = calcScale(image);
int iH = image.getImageHeight();
int iW = image.getImageWidth();
int newX = Math.round((iW / 2 - 25) * scale);
int newY = Math.round((iH / 2 - 200) * scale);

image.setScale(scale);
image.setPosition(newX, newY);
```

I cant use this anymore like this and In the ZoomAnimation I cant see how you are setting the position of the imageview.

Cheers,

Vadimo

**Comment by jasonpolites** [comment]
Hi Vad,

The ZoomAnimation doesn't change the view's position directly, rather it calls a listener which resides inside the gesture handler:

https://github.com/jasonpolites/gesture-imageview/blob/master/main/src/com/polites/android/GestureImageViewTouchListener.java#L127

**Comment by Vad1mo** [comment]
thank you I now got it. Just needed to change the vector direction, scale and it worked :)
