### ISSUE TITLE
Change picture of GestureImageView does not work.

### ISSUE THREAD

**Issue by keppelcao** [jasonpolites/gesture-imageview#21]
setImageBitmap/setImageDrawable/setImageResource does not work when call continuously.

These functions works very well if you call only  one time.
But if you call more than two time, the image disappeared.

**Comment by keppelcao** [comment]
I think initImage method should be this(it works well):

``` java
protected void initImage() {
        if (this.drawable != null) {
            this.drawable.setAlpha(alpha);
            this.drawable.setFilterBitmap(true);
            if (colorFilter != null) {
                this.drawable.setColorFilter(colorFilter);
            }
            // Keppel.Cao
            layout = false;
            startingScale = -1.0f;
        }

        if (!layout) {
            requestLayout();
            // Keppel.Cao
            // redraw();
            reset();
        }
}
```

**Comment by jasonpolites** [comment]
ok thanks for the report, and the fix.  I'll create a test case to reproduce and add the fix.

**Comment by ghost** [comment]
Oh god thanks keppelcao was exactly what I was looking to solve !

**Comment by Vince-s** [comment]
keppelcao, I will raise a statue in your glory ! Thanks a lot for your solution, you just saved my life !

**Comment by RhysDavis** [comment]
Why is this still not pulled into the main project =\

**Comment by longhoanggiang** [comment]
OK, it worked great. Thanks Keppel.Cao

**Comment by android-fred** [comment]
yes, the fix is really great. It works. Without it, when change image dynamically, and the touch or pinch the image, the image view will show blank screen.
With this fix, it really works fine. Suggest to add it to the trunk.

**Comment by xddxz** [comment]
veryGood ~~ one night  !find it

**Comment by mattster09** [comment]
Why does it display all the bitmaps upside down for me? and when i touch the image, it gets back to normal, however, then i am not able to do the pinch zoom. please help! totally new to android...

**Comment by jasonpolites** [comment]
Merged pull request

**Comment by MayuriKhinvasara** [comment]
'keppelcao' solution with change in initimage() worked for me. Thanks.
I was trying to switch images continuously, with setImageResource.

**Comment by antigravity99** [comment]
Thanks for the fix! Why has this not been fixed in 2 years?

**Comment by GowthamRayar** [comment]
Bravo

**Comment by iywgqt** [comment]
thanks a lot

**Comment by lbrvan** [comment]
perfect!
