### ISSUE TITLE
Using setScale seems to mess up internal state

### ISSUE THREAD

**Issue by Goddchen** [jasonpolites/gesture-imageview#28]
Hey everyone,

in my app i have a button that will set the scale to 1.0 by calling `setScale(1)`.
This doesn't work so i have to call `redraw()` afterwards.
This works for a short time. The image is adjusted. But as soon as i pan or zoom, it resets to its last zoom :(

Goddchen

**Comment by ralves-dev** [comment]
See my [issue](https://github.com/jasonpolites/gesture-imageview/issues/27)
