### ISSUE TITLE
Compilation failure on Android 4.0

### ISSUE THREAD

**Issue by jcogilvie** [jasonpolites/gesture-imageview#3]
This class makes use of Canvas.setViewport, which does not exist in Android 4.0 because it apparently didn't do anything at all.

See Romain Guy's post here:
http://grokbase.com/t/gg/android-developers/1234785x4t/where-did-canvas-setviewport-int-int-go-since-ics

**Comment by jasonpolites** [comment]
Mmm.. well spotted.  Not sure why it's doing this.. or why it works for me on Galaxy Nexus :/  I'll remove this from the code.

**Comment by jasonpolites** [comment]
Code removed :)
