### ISSUE TITLE
Is there a way to zoom buttons on top of the GestureImageView?

### ISSUE THREAD

**Issue by eddiekeane** [jasonpolites/gesture-imageview#34]
I have a series of buttons on a graphic which are positioned in order that they correspond to a part of the graphic. When I zoom in or out, the buttons stay where they were. Is there a way to make them zoom with the background or is there a function in GestureImageView that would let me read the parameters by which to move them (x,y) position and height/width?

**Comment by gfowley** [comment]
I solved a similar problem using a LayerDrawable consisting of the bitmap and a PictureDrawable the same size as the bitmap. Zoom and pan stays in sync with no work required by me.

(Using Ruby)

Create Picture:

``` ruby
@pic = android::graphics::Picture.new
@pic_canvas = @pic.beginRecording( @map.bitmap.getWidth, @map.bitmap.getHeight )
```

Draw on @pic_canvas, when done, create PictureDrawable:

``` ruby
@pic_drawable = android::graphics::drawable::PictureDrawable.new( @pic )
```

Assign LayerDrawable consisting of bitmap drawble and picture drawable to gesture image view:

``` ruby
@image_view.setImageDrawable(
  android::graphics::drawable::LayerDrawable.new(
    [
      android::graphics::drawable::BitmapDrawable.new( @map.bitmap ),
      @pic_drawable
    ]
  )
)
```

**Comment by jasonpolites** [comment]
LayerDrawable is definitely the right approach, but if you want your buttons to be "clickable this is going to get tricky.  One solution is to use a LayerDrawable as suggested and intercept the touch events on the image itself.  You'll have to inspect the zoom value and the center x,y to determine the x,y position of the click and whether it corresponds to one of your buttons.  A getZoom() method has just been added and will be pushed to github soon
