### ISSUE TITLE
Changing bitmaps requires another action before new bitmap displays

### ISSUE THREAD

**Issue by jcogilvie** [jasonpolites/gesture-imageview#5]
I have a loading image that I use before my actual image is download.  If I call setBitmap after the first image is already displayed, nothing happens.  I suspect you should call redraw() at the end of setBitmap and setResource.

**Comment by jcogilvie** [comment]
*nothing happens until I touch the image

**Comment by jcogilvie** [comment]
Relatedly, setting bitmap to null (which in the default ImageView case just displays nothing) causes an NPE in onMeasure (solved by a simple null check).

**Comment by jasonpolites** [comment]
NPE check should already be there.  I will add the redraw call on setters.

**Comment by jasonpolites** [comment]
Done.
