### ISSUE TITLE
Zooming out happens in-place then snaps back to top-left corner

### ISSUE THREAD

**Issue by jcogilvie** [jasonpolites/gesture-imageview#6]
When zooming out on an image that does not take up the whole View, pinching will render the image smaller, in-place where I pinched it.  After I let go, it snaps to the top-left corner of the view.

Can you tell I'm currently implementing stuff with this code?  ;)

Expected behavior would be either:

-Once the scaled image size < view size, leave the top-left corner anchored and only zoom the bottom right corner toward it, or
-Leave the image where I pinched it, offset from the corner

**Comment by jasonpolites** [comment]
OK.. I'll create a test case for this and see it I can resolve.  I'm working on something else right now, and switching back to this when I can so not sure if it will be resolved immediately.

Of course the alternative is that you fork the project and submit a pull request if you want to resolve it yourself :)

**Comment by jcogilvie** [comment]
We're working on it.  Unfortunately it's probably hard to pull from
bitbucket/hg to github.

On Sun, Apr 1, 2012 at 4:42 PM, Jason <
reply@reply.github.com

**Comment by jasonpolites** [comment]
Hmm.. how are you seeing this problem anyway?  The image should be auto-scaled to fill the view, so it should never not be taking up the whole view.  Can you post a code/layout example?

**Comment by jcogilvie** [comment]
I have a layout with this XML (mind you, this was before I downloaded your
latest changes that incorporated those bug fixes):

<com.polites.android.GestureImageView
        android:layout_width="wrap_content"
        android:layout_height="fill_parent"
    android:layout_weight="10"
    gesture-image:min-scale="0.1"
    gesture-image:max-scale="10.0"
        android:id="@+id/photo"
        android:scaleType="fitCenter"
        android:adjustViewBounds="true"
        android:gravity="top"
        android:layout_gravity="top"
        android:src="@drawable/icon_hires"
    />

It used to be an ImageView before I started using this project.  Of note:
this was before it extended ImageView so half of those attributes meant
nothing.

I set it to use icon_hires here in XML (that's the loading image) and then
later in code I set it to use an actual bitmap (as a BitmapDrawable) that
has been downloaded.

The image can scale down to be very small within the view's layout size.
 If I zoom out on it so that it is smaller than the full width of the
device's screen, upon releasing my fingers it snaps to the top left corner
of the view.

Does that answer your question?

On Sun, Apr 1, 2012 at 4:53 PM, Jason <
reply@reply.github.com

**Comment by jasonpolites** [comment]
Ahh I understand.  OK so the problem is that the layout of the view is only being computed once.  So when you set the initial image it is calculating the width/height etc based on this, then not recalculating after you set the new image.

I'll need to add a requestLayout call I think.  Let me see if I can create a test case...

**Comment by jasonpolites** [comment]
ok.. I added a requestLayout when the original image is changed.
