### ISSUE TITLE
Another null pointer when setting null drawable

### ISSUE THREAD

**Issue by jcogilvie** [jasonpolites/gesture-imageview#8]
Just grabbed your latest code and it's perfect!  It behaves exactly as I would expect.  Bravo!  :)

One small thing: I get an NPE in initImage if I set the Drawable to null (as is wise to do to when cleaning up after an Activity so as not to persist references).

**Comment by jasonpolites** [comment]
Thanks for catching this one.  I'll add some more null checks

**Comment by jasonpolites** [comment]
Fixed
