### ISSUE TITLE
Portrait orientation starts out full-size on too-tall images

### ISSUE THREAD

**Issue by jcogilvie** [jasonpolites/gesture-imageview#9]
Hi there!  Again.  :)

I have an image that's bigger vertically than horizontally (as an example, a screenshot of an average-sized android device while sitting in portrait orientation, displayed on said device).

When I put the device into landscape mode showing the same image, it's scaled properly (initially displays a zoomed-out image on the screen, but the canvas takes up the whole available width).

When I put it into portrait mode, if I have any header or footer on the page, the image shows up zoomed in to fit its width on the screen, at the expense of cutting off the height.

Perhaps there's a way to implement the android:scaleType attribute?  This may come as two different attributes for this view:  one to indicate the scale type for the view bounds (i.e., whether the canvas should wrap to the initial sizing of the image) and one to indicate the initial display.

I could for example set the scaleType to fitCenter, and then choose whether I want the canvas to take all available space so I can zoom to full size, or I want it to collapse the canvas down to wrap the initial image.

**Comment by jcogilvie** [comment]
I got it to be scaled for fitCenter by doing this in setupCanvas just before setting scaleAdjust:

startingScale = Math.min((float) measuredHeight / (float) imageHeight, (float) measuredWidth/ (float) imageWidth);

**Comment by jasonpolites** [comment]
Awesome.  I'll have a look at this snippet and if all looks good I'll add it to the master branch.

I've also just been playing with the image view on iPhone and I think this project is getting close to representing equivalent functionality.  Ideally I'd like to have thew two indistinguishable.

**Comment by jasonpolites** [comment]
Added support for CENTER, CENTER_INSIDE and CENTER_CROP scale types.  CENTER_INSIDE is the default if no scale type is specified.
